# Generated by Django 5.1.4 on 2025-09-06 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_review_review_socialmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.TextField(default='a desription of the profile'),
            preserve_default=False,
        ),
    ]
