# Generated by Django 5.1.4 on 2025-09-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='facebook',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='instagram',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='linkedIn',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='threads',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='x',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
