# Generated by Django 5.1.4 on 2025-09-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_socialmedia_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='phone_number',
            field=models.CharField(default=9876344902, max_length=20),
            preserve_default=False,
        ),
    ]
