# Generated by Django 5.1.4 on 2025-08-31 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='picture_url',
            field=models.URLField(default='https://google.com'),
        ),
    ]
