# Generated by Django 5.1.4 on 2025-09-03 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occupation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='occupation',
            name='icon',
            field=models.CharField(default='settings', max_length=100),
        ),
    ]
