# Generated by Django 5.1.4 on 2025-09-23 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occupation', '0002_occupation_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='occupation',
            name='picture_url',
            field=models.URLField(default='https://leapmax.ai/wp-content/uploads/2024/06/Flexible-work-arrangements.webp'),
        ),
    ]
